server:
  port: 8769
spring:
  application:
    name: gateway
#路由规则
  cloud:
    gateway:
      routes:
        - id: order-service   #路由的标识
          uri: lb://order-service #需要转发的地址
          predicates:
            - Path=/order-service/**  #断言规则
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: http://localhost:8847
        username: nacos
        password: nacos
